### ISSUE TITLE
CJSX messes up transformation

### ISSUE THREAD

**Issue by chintanparikh** [jsdf/sprockets-coffee-react#8] opened 2015-06-29 21:40 UTC
Check out http://stackoverflow.com/questions/31125721/react-component-rendering-to-string-for-some-reason

It was caused (I think) because of the CJSX transformation. It transformed authenticty_token_input.js.coffee.cjsx into 

```javascript
(function() {
  window.AuthenticityTokenInput = React.createClass({
    render: function() {
      return React.createElement("div", {
        "style": {
          margin: 0,
          padding: 0,
          padding: 'inline'
        },
        "input": true,
        "t": true,
        "name": "utf8",
        "type": "hidden",
        "value": "✓"
      }, "\x3Cinput name=\"authenticity_token\" type=\"hidden\" value=", this.props.authenticity_token, "\x3E");
    }
  });

}).call(this);

```

**Comment by jsdf** [comment] 2015-06-29 22:02
I replied on the [StackOverflow thread](http://stackoverflow.com/questions/31125721/react-component-rendering-to-string-for-some-reason), but for anyone else who might come across this issue, the explanation is as follows:

If you encounter tags being output as plain text when using CJSX, usually the cause is that one of the inner tags is malformed.

In your case it's the `<input>` tags, which should be self closing. In CJSX (and JSX) you must provide either a closing tag, or make the tag self closing, eg. `<input />`

**Closed by jsdf** 2015-06-29 22:02 UTC
